import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { BarChart, Bar, LineChart, Line, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import { Search, Map, SlidersHorizontal, Library, ArrowUpRight, ShieldCheck, Sparkles, FileText, Download, ChevronRight, X, LogIn, Users } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const demoUsers = [{role:"Public",email:"public@bhoomi.in",password:"public123"},{role:"Researcher",email:"researcher@bhoomi.in",password:"research123"},{role:"Official",email:"official@bhoomi.in",password:"official123"},{role:"Admin",email:"admin@bhoomi.in",password:"admin123"}];
const nav = [{id:"search",label:"Evidence search",icon:Search},{id:"analytics",label:"Dispute analytics",icon:Map},{id:"simulation",label:"Policy simulation",icon:SlidersHorizontal},{id:"workspace",label:"Research workspace",icon:Library}];

function App(){
 const [tab,setTab]=useState("search"); const [query,setQuery]=useState("What evidence exists on gender-inclusive land titling in India?"); const [results,setResults]=useState([]); const [synthesis,setSynthesis]=useState(null); const [analytics,setAnalytics]=useState(null); const [workspace,setWorkspace]=useState(null); const [selected,setSelected]=useState(null); const [loginOpen,setLoginOpen]=useState(false); const [user,setUser]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [analyticsError,setAnalyticsError]=useState(""); const [workspaceError,setWorkspaceError]=useState(""); const [sim,setSim]=useState({resolution_months:12,digitisation:78,women_titling:45}); const [simResult,setSimResult]=useState(null);
 useEffect(()=>{axios.get(`${API}/analytics`).then(r=>setAnalytics(r.data)).catch(()=>setAnalyticsError("Analytics are temporarily unavailable.")); axios.get(`${API}/workspace`).then(r=>setWorkspace(r.data)).catch(()=>setWorkspaceError("Workspace could not be loaded."));},[]);
 const search=async()=>{setLoading(true);setError("");try{const [s,a]=await Promise.all([axios.post(`${API}/search`,{query}),axios.post(`${API}/synthesis`,{query})]);setResults(s.data.results);setSynthesis(a.data)}catch{setError("The evidence service is unavailable. Please try again.")}finally{setLoading(false)}};
 // Initial load intentionally runs once; search uses the current default question.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(tab==="search"&&!results.length) search();},[]);
 const runSim=async()=>setSimResult((await axios.post(`${API}/simulation`,sim)).data);
 const roleLabel=user?.role||"Public access";
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">B</div><div><strong data-testid="brand-name">Bhoomi</strong><span>evidence commons</span></div></div><div className="side-label">Explore</div>{nav.map(n=>{const Icon=n.icon;return <button key={n.id} data-testid={`nav-${n.id}`} className={`nav-item ${tab===n.id?"active":""}`} onClick={()=>setTab(n.id)}><Icon size={18}/><span>{n.label}</span>{tab===n.id&&<ChevronRight size={15}/>}</button>})}<div className="sidebar-foot"><div className="verified-note"><ShieldCheck size={16}/><span>Evidence first<br/><small>Every claim has a source</small></span></div><button data-testid="login-open-button" className="login-button" onClick={()=>setLoginOpen(true)}><LogIn size={16}/>{user?user.role:"Sign in"}</button></div></aside>
 <main className="main-content"><header className="topbar"><div><span className="eyebrow">LAND GOVERNANCE · INDIA</span><h1 data-testid="page-title">{nav.find(n=>n.id===tab)?.label}</h1></div><div className="top-actions"><span data-testid="role-status" className="role-chip"><span className="role-dot"/>{roleLabel}</span><button data-testid="top-login-button" className="icon-button" onClick={()=>setLoginOpen(true)}><Users size={17}/></button></div></header>{tab==="search"&&<SearchView query={query} setQuery={setQuery} search={search} loading={loading} synthesis={synthesis} results={results} setSelected={setSelected} error={error}/>} {tab==="analytics"&&<AnalyticsView analytics={analytics} setSelected={setSelected} error={analyticsError}/>} {tab==="simulation"&&<SimulationView sim={sim} setSim={setSim} result={simResult} runSim={runSim}/>} {tab==="workspace"&&<WorkspaceView workspace={workspace} setSelected={setSelected} error={workspaceError}/>}</main>
 {selected&&<DocumentDrawer doc={selected} close={()=>setSelected(null)}/>} {loginOpen&&<LoginModal close={()=>setLoginOpen(false)} setUser={setUser}/>}</div>
}

function SearchView({query,setQuery,search,loading,synthesis,results,setSelected,error}){return <div className="content-wrap"><section className="search-hero"><div className="hero-copy"><div className="kicker"><Sparkles size={14}/> GROUNDED RESEARCH</div><h2>Find the evidence<br/><em>behind the decision.</em></h2><p>Search a curated corpus of India’s land governance research, reports, and case studies.</p></div><div className="search-box"><Search size={20}/><input data-testid="research-search-input" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()}/><button data-testid="research-search-button" onClick={search}>{loading?"Searching…":"Ask the corpus"}<ArrowUpRight size={16}/></button></div>{error&&<div data-testid="search-error" className="login-error">{error}</div>}<div className="hero-meta"><span><span className="green-dot"/> {results.length||5} relevant passages found</span><span>Corpus refreshed 06 Feb 2025</span></div></section>{synthesis&&<section className="answer-section"><div className="section-heading"><div><span className="section-kicker">SYNTHESIS · GPT 5.4</span><h3>What the evidence says</h3></div><span data-testid="grounding-badge" className="grounding-badge"><ShieldCheck size={14}/> Citation grounded</span></div><div className="answer-grid"><div className="answer-text" data-testid="sourced-answer">{synthesis.answer}</div><div className="answer-side"><span className="mini-label">TRACEABILITY</span><strong>{synthesis.citations.length} cited passages</strong><span>Click any source to open the original context.</span><button data-testid="export-bibliography-button" className="outline-button"><Download size={15}/> Export bibliography</button></div></div><div className="citation-row">{synthesis.citations.map((c,i)=><button key={c.document_id} data-testid={`citation-badge-${i}`} className="citation" onClick={()=>setSelected(results.find(r=>r.id===c.document_id)||{...c,title:c.title,passage:c.passage})}><span>{String(i+1).padStart(2,"0")}</span><span>{c.title}</span><ArrowUpRight size={14}/></button>)}</div></section>}<section className="results-section"><div className="section-heading"><div><span className="section-kicker">DOCUMENTS</span><h3>Relevant in the corpus</h3></div><button data-testid="view-all-documents-button" className="text-button">View all {results.length||5} documents <ArrowUpRight size={14}/></button></div><div className="doc-list">{results.map((d,i)=><button data-testid={`document-result-${i}`} className="doc-row" key={d.id} onClick={()=>setSelected(d)}><div className="doc-icon"><FileText size={19}/></div><div className="doc-main"><strong>{d.title}</strong><span>{d.author} · {d.year} · {d.pages}</span><p>{d.summary}</p></div><div className="doc-score"><span>{d.relevance}%</span><small>match</small></div><ChevronRight size={17}/></button>)}</div></section></div>}

function AnalyticsView({analytics,setSelected}){return <div className="content-wrap"><div className="notice illustrative"><span>ILLUSTRATIVE INDEX</span><p>District figures are demo-ready sample records shaped like LARR portal data. Connect the live feed before production use.</p></div><div className="stat-grid"><Stat label="Documents indexed" value={analytics?.documents||5} note="Curated corpus"/><Stat label="Disputes indexed" value="12,340" note="Last 3 years"/><Stat label="Digitisation" value={`${analytics?.digitisation||68}%`} note="Across 18 states"/><Stat label="Top hotspot" value="Bijnor" note="847 disputes"/></div><div className="analytics-grid"><section className="panel map-panel"><div className="panel-head"><div><span className="section-kicker">DISTRICT VIEW</span><h3>Dispute density map</h3></div><span className="map-legend"><i className="high"/> high <i className="medium"/> medium <i className="low"/> low</span></div><div className="india-map">{(analytics?.districts||[]).map((d,i)=><button data-testid={`district-${d.name.toLowerCase()}`} onClick={()=>setSelected({title:`${d.name} district profile`,summary:`${d.state} · ${d.count} indexed disputes`,passage:`Top categories: ${Object.entries(d.categories).map(([k,v])=>`${k} (${v})`).join(", ")}`,pages:"Analytics index"})} className={`district d${i}`} key={d.name}><span>{d.name}</span><strong>{d.count}</strong></button>)}</div></section><section className="panel chart-panel"><div className="panel-head"><div><span className="section-kicker">QUARTERLY TREND</span><h3>Filing volume</h3></div><span className="chart-note">2023 — 2024</span></div><ResponsiveContainer width="100%" height={250}><LineChart data={analytics?.quarters||[]}><CartesianGrid stroke="#e6e3dc" vertical={false}/><XAxis dataKey="quarter" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Line type="monotone" dataKey="value" stroke="#1e3a2f" strokeWidth={3} dot={{r:3,fill:"#d9822b"}}/></LineChart></ResponsiveContainer></section></div><section className="panel district-table"><div className="panel-head"><div><span className="section-kicker">HOTSPOTS</span><h3>Where attention is needed</h3></div><span className="chart-note">Click a district for detail</span></div>{(analytics?.districts||[]).map(d=><button data-testid={`district-row-${d.name.toLowerCase()}`} className="district-row" key={d.name} onClick={()=>setSelected({title:`${d.name} district profile`,summary:`${d.state} · ${d.count} indexed disputes`,passage:`Top categories: ${Object.entries(d.categories).map(([k,v])=>`${k} (${v})`).join(", ")}`,pages:"Analytics index"})}><span className={`density ${d.level}`}/><strong>{d.name}</strong><span>{d.state}</span><b>{d.count}</b><ChevronRight size={16}/></button>)}</section></div>}
function Stat({label,value,note}){return <div className="stat"><span>{label}</span><strong data-testid={`stat-${label.toLowerCase().replaceAll(" ","-")}`}>{value}</strong><small>{note}</small></div>}
function SimulationView({sim,setSim,result,runSim}){return <div className="content-wrap"><section className="sim-intro"><div><span className="section-kicker blue">TRANSPARENT MODEL</span><h2>Test a policy lever.<br/><em>Show your assumptions.</em></h2><p>This is not a prediction. It applies published effect sizes to a baseline so officials can discuss trade-offs openly.</p></div><div className="formula-card"><span>MODEL NOTE</span><strong>Base × (1 − effect size × change)</strong><small>Deterministic · 5 comparable states · Medium confidence</small></div></section><div className="simulation-grid"><section className="panel lever-panel"><div className="panel-head"><h3>Policy levers</h3><span className="chart-note">Adjust inputs</span></div><Lever label="Resolution time" value={sim.resolution_months} min={6} max={48} unit="months" onChange={v=>setSim({...sim,resolution_months:+v})} test="resolution-slider"/><Lever label="District digitisation" value={sim.digitisation} min={40} max={100} unit="%" onChange={v=>setSim({...sim,digitisation:+v})} test="digitisation-slider"/><Lever label="Women’s titling" value={sim.women_titling} min={20} max={80} unit="%" onChange={v=>setSim({...sim,women_titling:+v})} test="women-titling-slider"/><button data-testid="run-simulation-button" className="primary-button" onClick={runSim}>Run scenario <ArrowUpRight size={16}/></button></section><section className="panel outcome-panel"><span className="section-kicker blue">PROJECTED OUTCOME</span><div className="outcome-numbers"><div><small>Current baseline</small><strong>1,200</strong><span>disputes / year</span></div><div className="outcome-arrow">→</div><div><small>Scenario result</small><strong className="blue-text">{result?.projected_disputes||"—"}</strong><span>disputes / year</span></div></div>{result?<><div className="reduction"><strong>↓ {result.reduction_pct}%</strong><span>projected reduction</span></div><div className="confidence"><ShieldCheck size={16}/><div><strong>{result.confidence} confidence · {result.similar_states} similar states</strong><p>{result.assumptions[1]}</p></div></div><div className="source-list"><span>JUSTIFIED BY</span>{result.sources.map(s=><div key={s}><FileText size={14}/>{s}</div>)}</div></>:<div className="empty-outcome"><SlidersHorizontal size={24}/><p>Adjust the levers and run a scenario to see the transparent calculation.</p></div>}</section></div></div>}
function Lever({label,value,min,max,unit,onChange,test}){return <label className="lever" data-testid={`${test}-group`}><div><span>{label}</span><strong>{value} {unit}</strong></div><input data-testid={test} type="range" min={min} max={max} value={value} onChange={e=>onChange(e.target.value)}/><div className="range-labels"><span>{min} {unit}</span><span>{max} {unit}</span></div></label>}
function WorkspaceView({workspace,setSelected}){return <div className="content-wrap"><section className="workspace-head"><div><span className="section-kicker">YOUR RESEARCH SPACE</span><h2>{workspace?.title||"Women’s land rights evidence map"}</h2><p>One shared view of the documents, debates, and data sources shaping your argument.</p></div><button data-testid="export-workspace-button" className="outline-button"><Download size={15}/> Export report</button></section><div className="workspace-grid"><section><div className="workspace-section-title"><h3>Key documents</h3><span>{workspace?.documents?.length||0} pinned</span></div>{(workspace?.documents||[]).map((d,i)=><button data-testid={`workspace-document-${i}`} className="workspace-doc" key={d.id} onClick={()=>setSelected(d)}><div className="doc-icon orange"><FileText size={18}/></div><div><strong>{d.title}</strong><span>{d.author} · {d.year}</span><p>{d.summary}</p></div><ArrowUpRight size={15}/></button>)}</section><section><div className="workspace-section-title"><h3>Key debates</h3><span>1 thread</span></div><div className="debate"><div className="debate-line"/><span>DEBATE 01</span><h3>Titling vs. effective control</h3><p>Does documenting women’s ownership change bargaining power if local institutions remain informal?</p><div className="debate-tags"><span>Inheritance</span><span>Gender</span></div></div><div className="data-source"><DatabaseIcon/><div><span>DATA SOURCE</span><strong>DILRMP open reports</strong><small>Updated February 2025 · Public</small></div></div></section></div></div>}
function DatabaseIcon(){return <div className="database-icon">⌁</div>}
function DocumentDrawer({doc,close}){return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button data-testid="document-drawer-close" className="close-button" onClick={close}><X size={18}/></button><span className="section-kicker">DOCUMENT VIEWER</span><h2 data-testid="document-viewer-title">{doc.title}</h2><p className="drawer-meta">{doc.author||"Bhoomi evidence index"} · {doc.pages||"Evidence passage"}</p><div className="highlighted-passage"><span>HIGHLIGHTED PASSAGE</span><p data-testid="highlighted-passage">“{doc.passage}”</p></div><div className="drawer-note"><ShieldCheck size={16}/><span>This passage is the evidence anchor used in the synthesis.</span></div></aside></div>}
function LoginModal({close,setUser}){const [email,setEmail]=useState("researcher@bhoomi.in");const [password,setPassword]=useState("research123");const [error,setError]=useState("");const submit=async e=>{e.preventDefault();try{const r=await axios.post(`${API}/auth/login`,{email,password});setUser(r.data.user);close()}catch{setError("Try one of the demo accounts below.")}};return <div className="modal-backdrop"><form className="login-modal" onSubmit={submit}><button type="button" data-testid="login-close-button" className="close-button" onClick={close}><X size={18}/></button><span className="section-kicker">DEMO ACCESS</span><h2>Choose your lens.</h2><p>See the platform as a researcher, official, or public explorer.</p><label>Email<input data-testid="login-email-input" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input data-testid="login-password-input" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div data-testid="login-error" className="login-error">{error}</div>}<button data-testid="login-submit-button" className="primary-button">Sign in <ArrowUpRight size={16}/></button><div className="demo-accounts"><span>DEMO ACCOUNTS</span>{demoUsers.map(u=><button type="button" data-testid={`demo-role-${u.role.toLowerCase()}`} key={u.role} onClick={()=>{setEmail(u.email);setPassword(u.password)}}><b>{u.role}</b><small>{u.email}</small></button>)}</div></form></div>}
export default App;

